SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
from (select A.ANIMAL_ID ANIMAL_ID, A.ANIMAL_TYPE ANIMAL_TYPE, A.NAME NAME, A.SEX_UPON_INTAKE SEX_UPON_INTAKE, B.SEX_UPON_OUTCOME SEX_UPON_OUTCOME
     from ANIMAL_INS A inner join ANIMAL_OUTS B
     on A.ANIMAL_ID = B.ANIMAL_ID)
where (SEX_UPON_INTAKE not like 'Spayed%' and SEX_UPON_INTAKE not like 'Neutered%') and (SEX_UPON_OUTCOME like 'Spayed%' or SEX_UPON_OUTCOME like 'Neutered%')
order by ANIMAL_ID