SELECT PRODUCT_CODE, sum(PRICE * SALES_AMOUNT) as SALES
from (select A.PRODUCT_CODE PRODUCT_CODE, A.PRICE PRICE, B.SALES_AMOUNT SALES_AMOUNT
     from PRODUCT A inner join OFFLINE_SALE B
     on A.PRODUCT_ID = B.PRODUCT_ID)
group by PRODUCT_CODE
order by SALES desc, PRODUCT_CODE
